
name: railway部署
on:
  push:
    branches:
      - master
    paths:
      - "./github/workflows/railwayDeploy.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: git clone https://username:${{ secrets.SECRET }}@github.com/ATravelerGo/natours.git
      - run: ls
        working-directory: natours


        
