
name: railway部署
on:
  push:
    branches:
      - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: git clone https://username:${{ secrets.SECRET }}@github.com/ATravelerGo/nginx.git
      - run: | 
          ls
         
       


        
