
name: railway部署
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: 克隆要部署的仓库代码
        run: git clone https://username:${{ secrets.SECRET }}@github.com/ATravelerGo/natours.git
      - run: ls


        
